version: '3'
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    image: audit-from
    container_name: audit-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development

  # Add other services as needed
